### ISSUE TITLE
Robot Design

### ISSUE THREAD

**Issue by wmacaluso** [rcxking/wpi_sample_return_robot_challenge#1]
Creating a bug to discuss and collaborate on robot design.

**Comment by wmacaluso** [comment]
SCARA rover visualization:

![image](https://f.cloud.github.com/assets/2722785/1825097/cc4f3d4c-71a9-11e3-8b0b-9d9e54285ef3.png)

**Comment by jedediyah** [comment]
I wonder if the Kinect should be placed higher, and perhaps along with a HD camera for larger range of vision.  Maybe a third camera could be placed either on the gripper or at the workspace of the arm for more aid when grasping.

**Comment by lis12** [comment]
I think that it is better that we move Kinect to the back of the robot so that the kinect can see what is going on when the arm is moving.

**Comment by lis12** [comment]
![robot_assemble](https://f.cloud.github.com/assets/6280960/1829380/4052d2e4-72a9-11e3-80b6-817e2f001235.JPG)

Hi guys, I made a scooping robot in solidworks shown above so that we can compare different approaches ;)

**Comment by lis12** [comment]
Kinect can be placed on the top red shelf. The sketch is very rough. Please leave your comments.

**Comment by wmacaluso** [comment]
I like the simplicity of the scoop, and the straight path through the center of the bot that the sample would take. It would make the acquisition process very easy. 

How would this scooping robot turn? I'd imagine the front two wheels would need to be swivel/caster wheels.

**Comment by jedediyah** [comment]
I always agree with Will, the scoop definitely is the simplest in terms of object acquisition.
Right, steering is still an issue.  Also, would the scoop be retractable?  We can't drive around with it on the ground, since the terrain is mixed and uneven.

**Comment by lis12** [comment]
At the beginning, I was thinking that if we make the rear wheels very large and front wheels very small, then adjust the speed of the rear wheels will turn the robot without loosing to much energy. I think caster wheels is a better option than norm wheels. 

I agree that the scoop should be retractable ;)

I think that as this design is relatively easier to build, maybe we can make a quick prototype of it and try it out?

**Comment by wmacaluso** [comment]
I would love to prototype a scoop robot like the one you've described - Do we think it might be possible to work on both a rover-type and scoop-type robot simultaneously? That way if one or the other proves to be a problem we can focus our efforts on the other?

I should mention that I've worked with swivel-wheels before, and they suffer from one drawback - there are certain orientations of the swivel wheels that will prevent the wheel from pivoting (the effective "moment arm" becomes very weak, and the wheel can't swivel.)

Also will we know for certain that all objects will be "scoop-able"?

**Comment by jedediyah** [comment]
There's some description of the objects in the rules, but I think they will send actual specs at some point.  I think all objects should be scoopable, although very small ones could pose a challenge. I think the mandibles that scoop should overlap.  The object weight is less than 2 kg and each dimension is less than 20 cm.  

Maybe we could do both prototypes at once.  I suspect we won't know until everyone is back in Troy, just based on the lack of activity here on github.
